eBanking/eBanking/Controllers/BankAccountController.cs
using eBanking.Data;
using eBanking.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using eBanking.BusinessModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace eBanking.Controllers
{
    public class BankAccountController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<ApplicationUser> _userManager;

        public BankAccountController(ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager) 
        {
            _dbContext = dbContext ?? throw new ArgumentException(nameof(dbContext));
            _userManager = userManager ?? throw new ArgumentException(nameof(userManager));
        }

        // GET: /<controller>/
        private void PopulateCurrencies()
        {
            var currencies = _dbContext.Currencies.ToList();
            ViewData["Currencies"] = new SelectList(currencies, "Id", "Name");
        }
        public IActionResult Index()
        {
            PopulateCurrencies();
            return View();
        }

        [HttpPost]
        public IActionResult CreateNewAccount (CreateBankAccount account) {
            PopulateCurrencies();
            string userId = _userManager.GetUserId(User);
            
            ApplicationUser user = _dbContext.Users.Include(u => u.Accounts).First(s => s.Id == userId);
            if(user.Accounts.Exists(c => c.CurrencyId == account.CurrencyId))
            {
                ViewData["Message"] = "You already have account of this currency!";
                return View("Index");
            }

            _dbContext.BankAccounts.Add(new BankAccount { CurrencyId = account.CurrencyId, UserId = user.Id });
            _dbContext.SaveChanges();
            ViewData["Message"] = "Account created!";

            return View("Index");
        }
    }
  
}

eBanking/eBanking/Controllers/ConversionController.cs
using eBanking.BusinessModels;
using eBanking.Data;
using eBanking.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace eBanking.Controllers
{
    public class ConversionController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private UserManager<ApplicationUser> _userManager;

        public ConversionController(ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager)
        {
            _dbContext = dbContext ?? throw new ArgumentException(nameof(dbContext));
            _userManager = userManager ?? throw new ArgumentException(nameof(userManager));

        }
        // GET: /<controller>/
        private void PopulateCurrencies()
        {
            string userId = _userManager.GetUserId(User);
            ApplicationUser user = _dbContext.Users
                .Include("Accounts.Currency")
                .First(s => s.Id == userId);
            var currencies = user.Accounts.Select(a => a.Currency).ToList();
            var accounts = user.Accounts.ToList();

            ViewData["Accounts"] = accounts;
            ViewData["Currencies"] = new SelectList(currencies, "Id", "Name");
        }
        public IActionResult Index()
        {
            PopulateCurrencies();
            return View();
        }

        public IActionResult ConvertMoney(Conversion conversion)
        {
            PopulateCurrencies();
            string userId = _userManager.GetUserId(User);
            ApplicationUser user = _dbContext
                .Users
                .Include("Accounts.Currency")
                .First(s => s.Id == userId);

            if (conversion.CurrencyIdFrom == conversion.CurrencyIdTo)
            {
                ViewData["Message"] = "Select different accounts!";
                return View("Index");
            }

            BankAccount from = user.Accounts.First(a => a.CurrencyId == conversion.CurrencyIdFrom);
            BankAccount to = user.Accounts.First(a => a.CurrencyId == conversion.CurrencyIdTo);

            if (conversion.Amount > from.Balance)
            {
                ViewData["Message"] = "Not enough resources";
                return View("Index");
            }

            to.Balance += conversion.Amount * (decimal)(from.Currency.Rate / to.Currency.Rate);
            from.Balance -= conversion.Amount;

            _dbContext.SaveChanges();
            ViewData["Message"] = "Conversion completed!";
            return View("Index");
        }
    }
}

eBanking/eBanking/Controllers/InvestmentController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using eBanking.Models;
using System;
using eBanking.Services;

namespace eBanking.Controllers
{
    public class InvestmentController : Controller
    {
        private readonly IChartService _chartService;
        private readonly ICurrencyRateService _currencyRateService;

        public InvestmentController(IChartService chartService,
            ICurrencyRateService currencyRateService)
        {
            _chartService = chartService ?? throw new ArgumentException(nameof(chartService));
            _currencyRateService = currencyRateService ?? throw new ArgumentException(nameof(currencyRateService));
        }
        public void PopulateCurrencies()
        {
            var currencies = _currencyRateService.GetCurrencyList();
            ViewData["Currencies"] = new SelectList(currencies.OrderBy(x => x.Name), "Id", "Name");
            ViewData["Today"] = DateTime.Today.ToString("yyyy-MM-dd");
        }
        public IActionResult Index()
        {
            PopulateCurrencies();

            var currencies = _currencyRateService.GetCurrencyList();
            int currency1 = currencies.First(a => a.Name == "VEF").Id;
            int currency2 = currencies.First(a => a.Name == "RSD").Id;

            var investmentChart = new InvestmentChart
            {
                FirstCurrency = currency1,
                SecondCurrency = currency2,
                StartingDate = DateTime.Now.AddDays(-70),
                EndingDate = DateTime.Now.AddDays(30),
                RadioResponse = "LinearRegression",
                Alpha = 0.5
            };            
            ViewData["ChartJson"] = _chartService.PrepareInvestmentChart(investmentChart);
            return View(investmentChart);
        }
        public IActionResult ShowGraph(InvestmentChart investmentChart)
        {
            ViewData["ChartJson"] = _chartService.PrepareInvestmentChart(investmentChart);
            PopulateCurrencies();
            return View("Index", investmentChart);            
        }        
    }
}

eBanking/eBanking/Controllers/TasksController.cs
using eBanking.BusinessModels;
using eBanking.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace eBanking.Controllers
{
    public class TasksController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<ApplicationUser> _userManager;

        public TasksController(ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager)
        {
            _dbContext = dbContext ?? throw new ArgumentException(nameof(dbContext));
            _userManager = userManager ?? throw new ArgumentException(nameof(userManager));

        }
        private void PopulateTasks()
        {
            //string userId = _userManager.GetUserId(User);
            /*Transaction transactions = _dbContext.Users
                .Where(t => t.== 0);*/
            /*var currencies = user.Accounts.Select(a => a.Currency).ToList();
            var accounts = user.Accounts.ToList();*/

            /*
            to.Balance += (decimal) transaction.Amount;
            from.Balance -= (decimal) transaction.Amount;*/

            /*ViewData["Accounts"] = accounts;
            ViewData["Currencies"] = new SelectList(currencies, "Id", "Name");*/
        }
        public IActionResult Index()
        {
            var tasks = _dbContext.Transactions
                .Where(t => t.Status == TransactionStatus.PENDING)
                .Select(t => new Models.Task 
                {
                    Id = t.Id,
                    Sender = t.AccountFrom.ApplicationUser.UserName,
                    Receiver = t.AccountTo.ApplicationUser.UserName,
                    CurrentBalance = t.AccountFrom.Balance,
                    Amount = t.Amount,
                    Currency = t.AccountFrom.Currency.Name,
                })
                .ToList();
            return View(tasks);
        }

        public IActionResult ApproveTransaction(int taskId)
        {
            var transaction = _dbContext.Transactions
                .Include(t => t.AccountFrom)
                .Include(t => t.AccountTo)
                .First(t => t.Id == taskId);

            transaction.AccountTo.Balance += (decimal)transaction.Amount;
            transaction.AccountFrom.Balance -= (decimal)transaction.Amount;

            transaction.Status = TransactionStatus.APROVED;
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult RejectTransaction(int taskId)
        {
            var transaction = _dbContext.Transactions.First(t => t.Id == taskId).Status = TransactionStatus.CANCELED;
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

eBanking/eBanking/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="//cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
    <script src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js"></script>
    <!-- <script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>-->
    <title>@ViewData["Title"] - Currency Explorer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Currency Explorer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Client"))
                        {@*
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BankAccount" asp-action="Index">Your Account</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Conversion" asp-action="Index">Conversion</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transaction</a>
                            </li>*@

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ExchangeRate" asp-action="Index">Exchange rate</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Investment" asp-action="Index">Investment consluting</a>
                            </li>
                        }
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="Index">Pending Tasks</a>
                            </li>

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Currency Explorer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>